import re

from nlp_profiler.constants import NaN


### Alphanumeric
def gather_alpha_numeric(text: str) -> list:
    """
    Return a list of numeric numbers.

    Args:
        text (str) :


    (Generated by docly)
    """
    if not isinstance(text, str):
        return []

    return re.findall('[A-Za-z0-9]', text)


def count_alpha_numeric(text: str) -> int:
    """
    Count the number of numeric numbers.

    Args:
        text (str) :


    (Generated by docly)
    """
    if not isinstance(text, str):
        return NaN

    return len(gather_alpha_numeric(text))
