import re

from nlp_profiler.constants import NaN


### Non-alphanumeric
def gather_non_alpha_numeric(text: str) -> list:
    """
    Return a list of non - numeric numbers.

    Args:
        text (str) :


    (Generated by docly)
    """
    if not isinstance(text, str):
        return []

    return re.findall('[^A-Za-z0-9]', text)


def count_non_alpha_numeric(text: str) -> int:
    """
    Count number of numeric numbers.

    Args:
        text (str) :


    (Generated by docly)
    """
    if not isinstance(text, str):
        return NaN

    return len(gather_non_alpha_numeric(text))
