import re

from nlp_profiler.constants import NaN


### Numbers
def gather_whole_numbers(text: str) -> list:
    """
    Gather all whole numbers.

    Args:
        text (str) :


    (Generated by docly)
    """
    if not isinstance(text, str):
        return []

    return re.findall(r'[0-9]+', text)


def count_whole_numbers(text: str) -> int:
    """
    Count the number of whole numbers.

    Args:
        text (str) :


    (Generated by docly)
    """
    if not isinstance(text, str):
        return NaN

    return len(gather_whole_numbers(text))
