import re

from nlp_profiler.constants import NaN


### Count words
def gather_words(text: str) -> list:
    """
    Gather words from text.

    Args:
        text (str) :


    (Generated by docly)
    """
    if not isinstance(text, str):
        return []

    return re.findall(r'\b[^\d\W]+\b', text)


def count_words(text: str) -> int:
    """
    Count words in text.

    Args:
        text (str) :


    (Generated by docly)
    """
    if not isinstance(text, str):
        return NaN
    return len(gather_words(text))
